### PR TITLE
Extract APN list from CarrierSettings

### LINKED ISSUE #28: Import CarrierSettings extractor
* https://github.com/daradib/carriersettings-extractor
* https://github.com/GrapheneOS/device_google_coral/pull/5

I think it makes to have it done here, since we already have the factory images and the CarrierSettings app / protobufs.

Also makes it easier to deal with licensing, everything proprietary in one place.

For #15 this'll be fine, upstream includes the app / .pb directly, and we can just do it in a separate script to make it easier to add it here right now and migrate later as needed.

@daradib @thestinger thoughts?

### PR DESCRIPTION
**Pull request by mikeNG**
Fixes #28

Requires a change in platform/build to prevent copying the AOSP sample APN list.
Here's my proposed commit for CalyxOS: https://review.calyxos.org/c/CalyxOS/platform_build/+/584

### CODE REVIEW

**Comment by mikeNG** [comment]
Note: only tested on sargo & android 10, checking android 11 and the rest of the devices would be appreciated

**Comment by dan-v** [comment]
@mikeNG this change looks good to me. @daradib - curious if you have any thoughts on this change?

**Review by dan-v — APPROVED** [review]

**Comment by chirayudesai** [comment]
Converted to draft pending a test run, might need updates for Pixel 2

**Comment by chirayudesai** [comment]
This is fine on 10.

A quick test on 11 would be appreciated.
If you don't pick the `build/make` change linked the apn file here would just get ignored.

@mikeNG was looking into CarrierConfig overlay as well, but the `vendor.xml` mostly points to `com.google.android.ims` which might rely on gapps and thus can't be put into naked.

**Comment by chirayudesai** [comment]
Works. All devices build, and generated apns file looks good too.

**Comment by thestinger** [comment]
This doesn't work with AOSP due to the vendor whitelist feature.

**Comment by thestinger** [comment]
This doesn't work with AOSP even with the standard APN configuration copying disabled. Maybe it has to do with the vendor file whitelist feature. Regardless, it doesn't work.

**Comment by thestinger** [comment]
Also, worth noting that they let many of the apps in the factory images get outdated and update them via the Play Store. We need to check if there's an update to this app being served via the Play Store and use that instead.

**Comment by thestinger** [comment]
It's possible that this is not actually device-specific beyond the version of the app that's bundled, and should actually be handled outside of android-prepare-vendor by extracting this from the latest version of the app and replacing the APNs in AOSP.

**Pull request merged**
