### PR TITLE
coral/flame: fix build failure

### PR DESCRIPTION
**Pull request by danielfullmer**
Otherwise, build fails with:

```
build/make/core/Makefile:28: error: overriding commands for target `out/target/product/coral/vendor/lib/libgptutils.so', previously defined at build/make/core/base_rules.mk:480
```

Not sure why I encountered this and you hadn't. In any case, there is no reason to bring in `libgptutils.so` from the vendor image.

AOSP with coral/flame builds successfully with this patch. I haven't tested on a device since I don't have one.

---

As an aside, here are the differences between my built images and Google's images for `coral`:
`/vendor`: https://gist.github.com/danielfullmer/929f81a95e6c42a55e345ca1dfd082e0
`/system`: https://gist.github.com/danielfullmer/91e07a5b10a68831aafaa4750e0a9b96
Lines with `>` are for the built images, and lines with `<` are for Google's images.

(I have the tooling to generate these trivially, so I figured I would post here in case it's useful)

### CODE REVIEW

**Comment by dan-v** [comment]
@danielfullmer - oops! i didn't see you had already addressed this. i just pushed the same exact change.

**Comment by dan-v** [comment]
Gonna close this out, but much appreciated! @chirayudesai didn't see this issue because he has some changes from master on his side that resulted in him not bumping into this.

**Comment by danielfullmer** [comment]
No worries. I probably should have posted about this in one of the chat rooms to get feedback.

**Comment by chirayudesai** [comment]
It's great to see a PR so quickly after the repo creation.

We're on #AOSPAlliance on freenode.

**Pull request closed without merging**
