### PR TITLE
bramble: Initial support for Pixel 4a (5G)

### PR DESCRIPTION
**Pull request by chirayudesai**
* Based on redfin - Pixel 5

### CODE REVIEW

**Comment by chirayudesai** [comment]
Extracts fine with January builds. Untested otherwise.

**Comment by chirayudesai** [comment]
Doesn't boot. Further debugging remains pending.

**Comment by chirayudesai** [comment]
https://github.com/CIS-Mobile/android-prepare-vendor/tree/android11-redbull known working config (boots)

diff is mostly removing files (there's more here), but also makefile configuration which might be it.

**Review by coxtor — APPROVED** [review]

**Comment by chirayudesai** [comment]
Looking good, it's the exact same as redfin, apart from just changing the name.

**Pull request merged**
